---
name: tock
full_name: Tock

description: |
  18F uses Tock to track our time, so that we can bill clients accurately and meet our legal and regulatory obligations.

impact: |
  We built a web app that allows 18F employees to log the hours they spend on various projects.
  We use this information for client billing and for internal analytics on what our team is working on.
  
owner_type: project

stage: live

testable: true

licenses:
  tock:
    name: Public Domain (CC0)
    url: https://github.com/18F/tock/blob/master/LICENSE.md

partners:
- 18F

contact:
- url: https://github.com/18F/tock/issues
  text: Tock Issue Tracker

team:
- github: @joshuabailes
  role: product owner

- github: @abrouilette
  role: project manager
  
- github: @batemapf
  role: developer
  
- github: @annalee
  role: tech lead
  
- github: @maya
  role: front-end design and development
  
- github: @lauraponce
  role: research

type: app

links:
- url: https://tock.18f.gov/
  text: Tock production site

# What technologies are used in this project?
stack:
- Cloud.gov
- Cloud.gov authentication
- Docker
- Django

# What are the services used to supply project status information?
# Items:
# - name: Name of the service
#   category: Type of the service
#   url: URL for detailed information
#   badge: URL for the status badge
services:
- 

# Organizations or individuals who have adopted the project for their own use
# Items:
# - id: The name of the organization or individual
#   url: A URL to the user's version of the project
users:
- 

# Tags that describe the project or aspects of the project
tags:
- 
