# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_project_lead'),
        ('projects', '0012_auto_20160705_2231'),
    ]

    operations = [
    ]
