# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_merge_20160919_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitLossAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('accounting_string', models.CharField(max_length=200)),
            ],
        ),
    ]
