# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_profitlossaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='profit_loss_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ProfitLossAccount'),
        ),
    ]
