# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20161116_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitlossaccount',
            name='accounting_string',
            field=models.CharField(max_length=200, verbose_name='Accounting String'),
        ),
        migrations.AlterField(
            model_name='profitlossaccount',
            name='as_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='profitlossaccount',
            name='as_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='profitlossaccount',
            name='as_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='profit_loss_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ProfitLossAccount', verbose_name='Profit/loss Accounting String'),
        ),
    ]
