# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20161116_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profitlossaccount',
            name='as_active',
        ),
    ]
