# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_remove_profitlossaccount_as_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitlossaccount',
            name='account_type',
            field=models.IntegerField(choices=[(0, 'Revenue'), (1, 'Expense')], default=0),
        ),
    ]
