# Generated by Django 2.2.7 on 2019-12-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20171229_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='exclude_from_billability',
            field=models.BooleanField(default=False, help_text='Check if this project should be excluded from calculations of billable hours, e.g. Out of Office'),
        ),
    ]
