# Generated by Django 2.2.13 on 2020-06-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20200519_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='include_in_utilization',
            field=models.BooleanField(default=False, help_text='For handling microrequests, per github.com/18F/tock/issues/1084'),
        ),
    ]
