# Generated by Django 2.2.24 on 2021-08-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20200519_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_weekly_bill',
            field=models.BooleanField(default=False),
        ),
    ]
