# Generated by Django 2.2.24 on 2021-08-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_project_is_weekly_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_weekly_bill',
            field=models.BooleanField(default=False, help_text='Is this project under weekly billing. Note: checking this will set as allocation drop-list in reporting, otherwise person are expected to report in hours', verbose_name='Weekly Billing?'),
        ),
    ]
