# Generated by Django 2.2.10 on 2020-03-04 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization'),
        ),
    ]
