# Generated by Django 2.2.10 on 2020-03-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_unit_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='active',
            field=models.BooleanField(default=True, help_text='Uncheck if it is not a current business unit'),
        ),
    ]
