# Generated by Django 2.2.10 on 2020-03-04 22:09

from django.db import migrations
from django.utils.text import slugify

UNIT_CHOICES = (
        (0, 'Operations-Team Operations'),
        (1, 'Operations-Talent'),
        (2, 'Operations-Infrastructure'),
        (3, 'Operations-Front Office'),
        (4, 'Chapters-Acquisition'),
        (5, 'Chapters-Engineering'),
        (6, 'Chapters-Design'),
        (7, 'Chapters-Product'),
        (8, 'Chapters-Strategists'),
        (9, 'Business-Acquisition Services'),
        (10, 'Business-Custom Partner Solutions'),
        (11, 'Business-Learn'),
        (12, 'Business-Products & Platforms'),
        (13, 'Business-Transformation Services'),
        (14, 'PIF-Fellows'),
        (15, 'PIF-Operations'),
        (16, 'Unknown / N/A'),
        (17, 'Chapters-Account Management'),
        (18, 'Portfolio-Human Services'),
        (19, 'Portfolio-National Security & Intelligence')
    )


class Migration(migrations.Migration):
    #  Create unit objects from previous choice list

    dependencies = [
        ('organizations', '0005_unit_active'),
    ]


    def forward(apps, schema_editor):
        Unit = apps.get_model("organizations", "Unit")
        for unit_id, unit_name in UNIT_CHOICES:
            Unit.objects.get_or_create(id=unit_id, name=unit_name, slug=slugify(unit_name))

    def reverse(apps, schema_editor):
        Unit = apps.get_model("organizations", "Unit")
        Unit.objects.all().delete()

    operations = [migrations.RunPython(forward, reverse_code=reverse)]
