@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml

!global $ELEMENT_FONT_COLOR = "#Black"
!global $CONTAINER_BG_COLOR = "#LightSkyBlue"
!global $CONTAINER_BORDER_COLOR = "#Black"
!global $EXTERNAL_CONTAINER_BG_COLOR = "#LightGrey"
!global $EXTERNAL_CONTAINER_BORDER_COLOR = "#Black"

skinparam database<<container>> {
    StereotypeFontColor $ELEMENT_FONT_COLOR
    FontColor $ELEMENT_FONT_COLOR
    BackgroundColor $CONTAINER_BG_COLOR
    BorderColor $CONTAINER_BORDER_COLOR
}

skinparam rectangle<<external_container>> {
    StereotypeFontColor $ELEMENT_FONT_COLOR
    FontColor $ELEMENT_FONT_COLOR
    BackgroundColor $EXTERNAL_CONTAINER_BG_COLOR
    BorderColor $EXTERNAL_CONTAINER_BORDER_COLOR
}

skinparam database<<external_container>> {
    StereotypeFontColor $ELEMENT_FONT_COLOR
    FontColor $ELEMENT_FONT_COLOR
    BackgroundColor $EXTERNAL_CONTAINER_BG_COLOR
    BorderColor $EXTERNAL_CONTAINER_BORDER_COLOR
}

skinparam rectangle<<container>> {
    StereotypeFontColor $ELEMENT_FONT_COLOR
    FontColor $ELEMENT_FONT_COLOR
    BackgroundColor $CONTAINER_BG_COLOR
    BorderColor $CONTAINER_BORDER_COLOR
}

skinparam Arrow {
    Color Black
    FontColor Black
}

skinparam rectangle<<boundary>> {
    FontColor Black
    BorderColor Black
}

System_Boundary(atob, "ATO Boundary") {
    Container(app, "Tock", "process within ATO boundary")
}
Container_Ext(browser, "Web Browser", "external entity")
Container_Ext(api_client, "Tock API Client", "external entity")
ContainerDb(cloudgov_services, "RDS", "cloud.gov datastore")
Container_Ext(newrelic, "New Relic", "external entity")
Container_Ext(cloudgov_logdrain, "Cloud.gov ELK", "external entity")

Rel(browser, app, "web page request")
Rel(app, browser, "HTML, JavaScript, CSS")
Rel(api_client, app, "API request with key")
Rel(app, api_client, "Tock data as JSON response")
Rel(cloudgov_services, app, "Timekeeping data rows")
Rel(app, cloudgov_services, "Timekeeping data queries")
Rel(app, cloudgov_services, "Timekeeping data as row imports")
Rel(app, newrelic, "Monitoring data")
Rel(app, cloudgov_logdrain, "Log data")
@enduml