@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Deployment.puml


title Tock typical network interactions

note as EncryptionNote
  All connections depicted are encrypted with TLS 1.2 unless otherwise noted.
end note


Deployment_Node(aws, "AWS GovCloud", "Amazon Web Services Region") {
	System_Ext(aws_alb, "Cloud.gov elastic load balancer", "ELB")
	Deployment_Node(cloudgov, "cloud.gov", "Cloud Foundry PaaS") {
        System_Ext(cloudgov_router, "cloud.gov router", "Cloud Foundry service")
        System_Ext(cloudgov_logdrain, "logs.fr.cloud.gov", "ELK")
        System_Ext(cloudgov_uaa, "cloud.gov User Authentication Server", "UAA (proxied to GSA secureauth)")


        ContainerDb(cloudgov_services, "cloud.gov data services", "AWS RDS", "Stores persistent data for apps")

        Boundary(atob, "ATO boundary") {
            Deployment_Node(organization, "Tock organization") {
                Deployment_Node(space, "Tock spaces") {
                    System(app, "Production", "tock.18f.gov")
                    System(app_staging, "Staging", "tock.app.cloud.gov", )
}
            }
        }
    }
}

Rel(aws_alb, cloudgov_router, "sends application traffic", "https (443)")
Rel(app, cloudgov_services, "read/write (variable)", "password auth")
Rel(app_staging, cloudgov_services, "read/write (variable)", "password auth")


' Logs flow
Rel(app, cloudgov_logdrain, "logs to", "stdout/stderr")
Rel(app_staging, cloudgov_logdrain, "logs to", "stdout/stderr")


' User access
Person_Ext(public, "Tock User")
Deployment_Node(computer, "Computing Device", "MS Windows, OS X, or Linux"){
    System_Ext(browser, "Web Browser")
    System_Ext(api_client, "API Client")
}


' Monitoring
Boundary(gsa_saas, "GSA-authorized SaaS") {
	System_Ext(dap, "DAP", "Web analytics SaaS")
	System_Ext(newrelic, "New Relic", "Monitoring SaaS")
}

Rel_L(newrelic, aws_alb, "monitors application", "https GET (443)")
Rel(app, newrelic, "reports telemetry", "tcp (443) w/ token")
Rel(public, browser, "uses")
Rel(public, api_client, "uses")

browser --> dap : **reports usage** \n//[https (443)]//

Rel(browser, aws_alb, "interacts with application", "https GET/POST (443)")
Rel(browser, cloudgov_uaa, "authenticates with MFA", "https GET/POST (443)")

Rel(api_client, aws_alb, "interacts with application", "https GET (443) w/ token")

Rel(cloudgov_router, app, "proxies to", "https GET/POST (443)")
Rel(cloudgov_router, app_staging, "proxies to", "https GET/POST (443)")

@enduml
