# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0022_auto_20160708_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecardobject',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
