# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employeegrade'),
        ('hours', '0022_auto_20160708_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecardobject',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.EmployeeGrade'),
        ),
    ]
