# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0023_timecardobject_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingperiod',
            name='target_billable_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
