# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0023_timecardobject_submitted'),
        ('hours', '0023_timecardobject_grade'),
    ]

    operations = [
    ]
