# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0024_reportingperiod_target_billable_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingperiod',
            name='target_billable_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
