# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 02:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0024_merge_20160919_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timecards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timecardobject',
            name='timecard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timecardobjects', to='hours.Timecard'),
        ),
    ]
