# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20161116_1248'),
        ('hours', '0025_auto_20161014_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecardobject',
            name='profit_loss_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ProfitLossAccount'),
        ),
    ]
