# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20161116_1452'),
        ('hours', '0026_timecardobject_profit_loss_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timecardobject',
            name='profit_loss_account',
        ),
        migrations.AddField(
            model_name='timecardobject',
            name='expense_profit_loss_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_profit_loss_account_', to='projects.ProfitLossAccount'),
        ),
        migrations.AddField(
            model_name='timecardobject',
            name='revenue_profit_loss_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_profit_loss_account_', to='projects.ProfitLossAccount'),
        ),
    ]
