# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20161116_1452'),
        ('hours', '0027_auto_20161116_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayPrefills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_period', models.PositiveSmallIntegerField(default=8)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'Holiday Prefills',
                'verbose_name_plural': 'Holiday Prefills',
                'ordering': ['project__name'],
            },
        ),
        migrations.AddField(
            model_name='reportingperiod',
            name='holiday_prefills',
            field=models.ManyToManyField(blank=True, help_text='Select items to prefill in timecards for this period. To create additional items, click the green "+" sign.', to='hours.HolidayPrefills'),
        ),
        migrations.AlterUniqueTogether(
            name='holidayprefills',
            unique_together=set([('project', 'hours_per_period')]),
        ),
    ]
