# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0027_auto_20161116_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Targets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(unique=True)),
                ('end_date', models.DateField(unique=True)),
                ('revenue_target', models.PositiveIntegerField(blank=True, null=True)),
                ('hours_target', models.PositiveIntegerField(blank=True, null=True)),
                ('periods', models.PositiveSmallIntegerField(default=52)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='targets',
            unique_together=set([('start_date', 'end_date')]),
        ),
    ]
