# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0027_auto_20161116_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Targets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(unique=True)),
                ('end_date', models.DateField(unique=True)),
                ('hours_target_cr', models.PositiveIntegerField(default=0, verbose_name='Hours target for cost recovery')),
                ('hours_target_plan', models.PositiveIntegerField(default=0, verbose_name='Hours target for financial plan')),
                ('revenue_target_cr', models.PositiveIntegerField(default=0, verbose_name='Revenue target for financial plan')),
                ('revenue_target_plan', models.PositiveIntegerField(default=0, verbose_name='Revenue target for financial plan')),
                ('periods', models.PositiveSmallIntegerField(default=52)),
                ('labor_rate', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Targets',
                'verbose_name': 'Target',
            },
        ),
        migrations.AlterUniqueTogether(
            name='targets',
            unique_together=set([('start_date', 'end_date')]),
        ),
    ]
