# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0028_auto_20161130_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='targets',
            options={'verbose_name': 'Target', 'verbose_name_plural': 'Targets'},
        ),
        migrations.RemoveField(
            model_name='targets',
            name='hours_target',
        ),
        migrations.RemoveField(
            model_name='targets',
            name='revenue_target',
        ),
        migrations.AddField(
            model_name='targets',
            name='hours_target_cr',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hours target for cost recovery'),
        ),
        migrations.AddField(
            model_name='targets',
            name='hours_target_plan',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hours target for financial plan'),
        ),
        migrations.AddField(
            model_name='targets',
            name='revenue_target_cr',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Revenue target for financial plan'),
        ),
        migrations.AddField(
            model_name='targets',
            name='revenue_target_plan',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Revenue target for financial plan'),
        ),
    ]
