# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-27 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0028_auto_20161125_1616'),
        ('hours', '0028_auto_20161201_1408'),
    ]

    operations = [
    ]
