# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-06 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0029_merge_20170227_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportingperiod',
            name='max_working_hours',
        ),
        migrations.RemoveField(
            model_name='reportingperiod',
            name='min_working_hours',
        ),
    ]
