# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-03 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0029_merge_20170227_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimecardNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The heading that will appear above the note when displayed in a timecard.', max_length=140)),
                ('body', models.TextField(help_text='The body of the note that will appear when displayed in a timecard.')),
                ('enabled', models.BooleanField(default=True, help_text='Toggle whether or not the note is displayed in a timecard.')),
                ('style', models.CharField(choices=[('info', 'Blue (Info)'), ('success', 'Green (Success)'), ('warning', 'Yellow (Warning)'), ('error', 'Red, (Error)')], default='info', help_text='The style in which to display the note in a timecard.', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
            ],
        ),
    ]
