# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0029_auto_20161130_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targets',
            name='hours_target_cr',
            field=models.PositiveIntegerField(default=0, verbose_name='Hours target for cost recovery'),
        ),
        migrations.AlterField(
            model_name='targets',
            name='hours_target_plan',
            field=models.PositiveIntegerField(default=0, verbose_name='Hours target for financial plan'),
        ),
        migrations.AlterField(
            model_name='targets',
            name='revenue_target_cr',
            field=models.PositiveIntegerField(default=0, verbose_name='Revenue target for financial plan'),
        ),
        migrations.AlterField(
            model_name='targets',
            name='revenue_target_plan',
            field=models.PositiveIntegerField(default=0, verbose_name='Revenue target for financial plan'),
        ),
    ]
