# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-04 02:07
from __future__ import unicode_literals

from django.db import migrations


def add_initial_timecard_note(apps, schema_editor):
    """
    Add a default TimecardNote model to be present in the app right at the
    start.
    """

    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    TimecardNote = apps.get_model('hours', 'TimecardNote')

    initial_timecard_note = TimecardNote(
        title='When to submit your time card',
        body='Submit your time card for the week by the end of the day on Friday (or the last business day of the week). If you are authorized to work on Saturday for any reason, enter and submit your time by the end of the day on Saturday.'
    )
    initial_timecard_note.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0030_timecardnote'),
    ]

    operations = [
        migrations.RunPython(add_initial_timecard_note),
    ]
