# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0030_auto_20161130_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='targets',
            name='labor_rate',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
