# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-04 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0031_auto_20171003_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timecardnote',
            options={'verbose_name': 'Timecard Note', 'verbose_name_plural': 'Timecard Notes'},
        ),
        migrations.AddField(
            model_name='reportingperiod',
            name='message_enabled',
            field=models.BooleanField(default=False, help_text='Toggle whether or not the message is displayed for the specific reporting period and visible in a Timecard.'),
        ),
        migrations.AddField(
            model_name='reportingperiod',
            name='message_style',
            field=models.CharField(choices=[('info', 'Blue (Info)'), ('success', 'Green (Success)'), ('warning', 'Yellow (Warning)'), ('error', 'Red (Error)')], default='info', help_text='The style in which to display the message in a reporting period.', max_length=32),
        ),
        migrations.AddField(
            model_name='reportingperiod',
            name='message_title',
            field=models.CharField(blank=True, help_text='An optional title to appear with the message.', max_length=140),
        ),
        migrations.AlterField(
            model_name='reportingperiod',
            name='message',
            field=models.TextField(blank=True, help_text='A message to provide at the top of the reporting period. This will appear above any Timecard Notes in a Timecard.'),
        ),
        migrations.AlterField(
            model_name='timecardnote',
            name='style',
            field=models.CharField(choices=[('info', 'Blue (Info)'), ('success', 'Green (Success)'), ('warning', 'Yellow (Warning)'), ('error', 'Red (Error)')], default='info', help_text='The style in which to display the note in a timecard.', max_length=32),
        ),
    ]
