# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0032_auto_20171003_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecardobject',
            name='expense_profit_loss_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_profit_loss_account', to='projects.ProfitLossAccount'),
        ),
        migrations.AlterField(
            model_name='timecardobject',
            name='revenue_profit_loss_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_profit_loss_account', to='projects.ProfitLossAccount'),
        ),
    ]
