# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-29 16:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0023_auto_20171229_1156'),
        ('hours', '0033_auto_20171221_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimecardPrefillData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, help_text='The amount of hours this user is assigned to this project.', max_digits=5)),
                ('notes', models.TextField(blank=True, default='', help_text='Any additional notes specific to this assignment.')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timecard_prefill_data', to='projects.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timecard_prefill_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='timecardprefilldata',
            unique_together=set([('user', 'project')]),
        ),
    ]
