# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-29 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0036_timecardprefill-to-employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timecardprefilldata',
            name='user',
        ),
    ]
