# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-30 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0039_auto_20180109_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecardprefilldata',
            name='end_date',
            field=models.DateField(blank=True, help_text='Optional end date for when this record should no longer be used.', null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='timecardprefilldata',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Toggle whether or not this record is active and used.'),
        ),
        migrations.AddField(
            model_name='timecardprefilldata',
            name='start_date',
            field=models.DateField(blank=True, help_text='Optional start date for when this record should be used.', null=True, verbose_name='Start Date'),
        ),
    ]
