# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import hours.models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0040_auto_20180130_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecardnote',
            name='position',
            field=models.SmallIntegerField(default=hours.models.get_next_timecard_position, help_text='The order in which this timecard note should be displayed.'),
        ),
        migrations.AlterField(
            model_name='reportingperiod',
            name='message',
            field=models.TextField(blank=True, help_text='A message to provide at the top of the reporting period. This will appear above any Timecard Notes in a Timecard. Note: supports Markdown.'),
        ),
        migrations.AlterField(
            model_name='timecardnote',
            name='body',
            field=models.TextField(help_text='The body of the note that will appear when displayed in a timecard. Note: supports Markdown.'),
        ),
    ]
