# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-02 18:43
from __future__ import unicode_literals

from django.db import migrations

from hours.utils import render_markdown

def render_notes(apps, schema_editor):
    """Pre-rendering notes"""
    TimecardNote = apps.get_model('hours', 'TimecardNote')
    ReportingPeriod = apps.get_model('hours', 'ReportingPeriod')

    for note in TimecardNote.objects.all():
        if note.body:
            note.rendered_body = render_markdown(note.body)
            note.save()

    for rp in ReportingPeriod.objects.all():
        if rp.message:
            rp.rendered_message = render_markdown(rp.message)
            rp.save()

def reverse(apps, schema_editor):
    TimecardNote = apps.get_model('hours', 'TimecardNote')
    ReportingPeriod = apps.get_model('hours', 'ReportingPeriod')

    for note in TimecardNote.objects.all():
        if note.rendered_body:
            note.rendered_body = ""
            note.save()

    for rp in ReportingPeriod.objects.all():
        if rp.message:
            rp.rendered_message = ""
            rp.save()

class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0042_auto_20181002_1535'),
    ]

    operations = [
        migrations.RunPython(render_notes, reverse)
    ]
