# Generated by Django 2.0.9 on 2019-01-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0043_notes_rendered'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Targets',
        ),
    ]
