# Generated by Django 2.0.9 on 2019-01-25 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0044_delete_targets'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timecardobject',
            unique_together=set(''),
        ),
    ]
