# Generated by Django 2.2.7 on 2019-12-04 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20171229_1156'),
        ('hours', '0046_deferrable_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timecardobject',
            name='submitted',
        ),
    ]
