# Generated by Django 2.2.7 on 2019-12-19 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_project_exclude_from_billability'),
        ('hours', '0047_auto_20191204_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecard',
            name='billable_expectation',
            field=models.DecimalField(decimal_places=2, default=0.8, max_digits=3, validators=[django.core.validators.MaxValueValidator(limit_value=1)], verbose_name='Percentage of hours which are expected to be billable this week'),
        ),
    ]
