# Generated by Django 2.2.10 on 2020-03-04 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20200303_1955'),
        ('hours', '0048_auto_20191219_0925'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timecardobject',
            unique_together={('timecard', 'project')},
        ),
    ]
