# Generated by Django 2.2.10 on 2020-03-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0050_auto_20200303_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='billable_hours',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True, verbose_name='# of hours which were billable'),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='excluded_hours',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True, verbose_name='# of hours which were excluded from utilization calculations (e.g. Out of office)'),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='non_billable_hours',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True, verbose_name='# of hours which were non-billable'),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='target_hours',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True, verbose_name='# of hours which were expected to be billable'),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='utilization',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True, verbose_name='Calculated Utilization for this timecard'),
        ),
    ]
