# Generated by Django 2.2.12 on 2020-04-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0050_auto_20200403_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecardnote',
            name='display_period_end',
            field=models.DateTimeField(help_text='The end time for displaying this note. Note: manually enabling will override this setting.', null=True),
        ),
        migrations.AddField(
            model_name='timecardnote',
            name='display_period_start',
            field=models.DateTimeField(help_text='The start time for displaying this note. Note: manually enabling will override this setting.', null=True),
        ),
    ]
