# Generated by Django 2.2.12 on 2020-04-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0051_auto_20200422_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecardnote',
            name='display_period_end',
            field=models.DateTimeField(blank=True, help_text='The end time for displaying this note. Note: manually enabling will override this setting.', null=True),
        ),
        migrations.AlterField(
            model_name='timecardnote',
            name='display_period_start',
            field=models.DateTimeField(blank=True, help_text='The start time for displaying this note. Note: manually enabling will override this setting.', null=True),
        ),
    ]
