# Generated by Django 2.2.19 on 2021-03-18 19:08

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0060_auto_20200702_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecard',
            name='submitted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
