# Generated by Django 2.2.24 on 2021-08-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0061_timecard_submitted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecardobject',
            name='project_allocation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
