# Generated by Django 3.2.16 on 2022-12-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0064_small_allocation2'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecard',
            name='total_allocation_hours',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, default=0, verbose_name='# of hours which are calculated from weekly allocation %'),
        ),
        migrations.AddField(
            model_name='timecard',
            name='total_weekly_allocation',
            field=models.DecimalField(blank=True, decimal_places=5, editable=False, max_digits=6, default=0, verbose_name='total weekly allocation %, sum of project_allocation from related timecardobjects'),
        ),
    ]
