# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_merge'),
        ('employees', '0009_auto_20160630_0150'),
    ]

    operations = [
    ]
