# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 20:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0011_merge_20160919_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='new_staff_reports',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Persons supervised by employee'),
        ),
    ]
