# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 20:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0012_auto_20160927_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='new_staff_reports',
        ),
        migrations.AddField(
            model_name='userdata',
            name='is_supervisor',
            field=models.BooleanField(default=False, verbose_name='Has supervisory responsibility'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
