# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_auto_20160915_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeegrade',
            name='g_start_date',
            field=models.DateField(help_text='Please select a start date for this grade.', verbose_name='Grade start date'),
        ),
        migrations.AlterField(
            model_name='employeegrade',
            name='grade',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, 'SES')], help_text='Please select a GS grade level.', unique_for_date='g_start_date'),
        ),
    ]
