# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_merge_20160919_1829'),
        ('employees', '0013_auto_20160916_1942'),
    ]

    operations = [
    ]
