# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_merge_20160920_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='float_people_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Float "people_id" attribute'),
        ),
    ]
