# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_userdata_float_people_id'),
        ('employees', '0017_auto_20161116_1535'),
    ]

    operations = [
    ]
