# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0029_auto_20161214_1906'),
        ('employees', '0017_auto_20161116_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeegrade',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='is_18f_employee',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='is_billable',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='profit_loss_account',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='unit',
        ),
        migrations.DeleteModel(
            name='EmployeeGrade',
        ),
    ]
