# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_merge_20170628_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='float_people_id',
            field=models.IntegerField(null=True, verbose_name='Float "people_id" attribute'),
        ),
    ]
