# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_auto_20170710_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='float_people_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Float "people_id" attribute'),
        ),
    ]
