# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_auto_20170710_1131'),
        ('employees', '0018_userdata_is_aws_eligible'),
    ]

    operations = [
    ]
