# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-03 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_merge_20170710_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='float_people_id',
        ),
    ]
