# Generated by Django 2.2.10 on 2020-03-04 00:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_userdata_billable_expectation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='billable_expectation',
            field=models.DecimalField(decimal_places=2, default=0.8, max_digits=3, validators=[django.core.validators.MaxValueValidator(limit_value=1)], verbose_name='Percentage of hours (expressed as a decimal) expected to be billable each week'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(0, 'Operations-Team Operations'), (1, 'Operations-Talent'), (2, 'Operations-Infrastructure'), (3, 'Operations-Front Office'), (4, 'Chapters-Acquisition'), (5, 'Chapters-Engineering'), (6, 'Chapters-Design'), (7, 'Chapters-Product'), (9, 'Business-Acquisition Services'), (10, 'Business-Custom Partner Solutions'), (11, 'Business-Learn'), (12, 'Business-Products & Platforms'), (13, 'Business-Transformation Services'), (14, 'PIF-Fellows'), (15, 'PIF-Operations'), (16, 'Unknown / N/A'), (17, 'Chapters-Account Management'), (18, 'Portfolio-Human Services'), (19, 'Portfolio-National Security & Intelligence')], null=True, verbose_name='Select 18F unit'),
        ),
    ]
