# Generated by Django 2.2.10 on 2020-03-03 16:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '__first__'),
        ('employees', '0025_userdata_billable_expectation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='billable_expectation',
            field=models.DecimalField(decimal_places=2, default=0.8, max_digits=3, validators=[django.core.validators.MaxValueValidator(limit_value=1)], verbose_name='Percentage of hours (expressed as a decimal) expected to be billable each week'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Unit', verbose_name='Select organization unit'),
        ),
    ]
