# Generated by Django 2.2.10 on 2020-03-03 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_userdata_billable_expectation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='billable_expectation',
            field=models.DecimalField(decimal_places=2, default=0.8, max_digits=3, validators=[django.core.validators.MaxValueValidator(limit_value=1)], verbose_name='Percentage of hours (expressed as a decimal) expected to be billable each week'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='unit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Select 18F unit'),
        ),
    ]
