# Generated by Django 2.2.10 on 2020-03-10 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0026_auto_20200303_1821'),
        ('organizations', '0006_unit_initial_data'),

    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='The business unit within the organization in which this person sits.', null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Unit', verbose_name='Business Unit'),
        ),
    ]
