# Generated by Django 2.2.10 on 2020-03-03 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_unit'),
        ('employees', '0026_auto_20200303_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Unit', verbose_name='Organization business unit'),
        ),
    ]
