# Generated by Django 2.2.12 on 2020-04-28 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0028_remove_userdata_is_billable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization'),
        ),
    ]
