# Generated by Django 2.2.12 on 2020-05-15 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0032_remove_userdata_billable_expectation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='expected_billable_hours',
            field=models.IntegerField(default=32, help_text='Number of hours expected to be billable in a 40 hour work week', validators=[django.core.validators.MaxValueValidator(limit_value=40)]),
        ),
    ]
