# Generated by Django 2.2.12 on 2020-05-29 16:30

from django.db import migrations, models
import django.db.models.deletion
from django.core.exceptions import ObjectDoesNotExist

def backfillorgs(apps, schema_editor):
    Employees = apps.get_model('employees','UserData')

    for orgs in Employees.all():
        try:
            i = 1
            org_data = Employees.objects.get(organization=null)
            orgs.organization = org_data.organization
            orgs.organization = i
            orgs.save
            i++
        except ObjectDoesNotExist:
            pass 

class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0033_auto_20200515_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization'),
        ),
        migrations.RunPython(backfillorgs)
    ]
