# Generated by Django 2.2.24 on 2021-08-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0034_auto_20200604_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='expected_project_allocation',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=5, null=True),
        ),
    ]
