# Generated by Django 3.2.6 on 2021-09-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0036_alter_userdata_expected_project_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='expected_project_allocation',
            field=models.DecimalField(blank=True, decimal_places=3, default=1.0, help_text='Enter in Decimal Format (ex. 1.00 = 100%, 0.50 = 50%)', max_digits=6, null=True, verbose_name='Expected Project Allocation'),
        ),
    ]
